name: Build and Release macOS Binary

on:
  push:
    tags:
      - 'v*'  # Triggers on version tags like v1.0.0, v2.1.3, etc.

jobs:
  build-macos:
    runs-on: macos-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Xcode
      uses: maxim-lobanov/setup-xcode@v1
      with:
        xcode-version: latest-stable

    - name: Build macOS binary
      run: |
        swift build -c release --arch arm64 --arch x86_64

    - name: Create binary archive
      run: |
        cd .build/apple/Products/Release
        tar -czf $GITHUB_WORKSPACE/yclock.tar.gz yclock

    - name: Create Release
      uses: softprops/action-gh-release@v1
      with:
        files: yclock.tar.gz
        draft: false
        prerelease: false
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
